spring:
    application:
        name: meta-crm
    profiles:
        active: dev
    cloud:
        nacos:
            discovery:
                server-addr: localhost:8848
                contextPath: /nacos
                password: nacos
                username: nacos
            config:
                server-addr: localhost:8848
                file-extension: yml
#            shared-configs:
#              - $(spring.application.name}-$(spring.profiles.active}.$spring.cloud.nacos.config.file-extension}

management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 8081

