spring:
    application:
        name: nacos-client
    cloud:
        nacos:
            discovery:
                namespace: public
                password: nacos
                server-addr: 127.0.0.1:8848
                username: nacos
