spring:
    application:
        name: meta-crm
    cloud:
        nacos:
            discovery:
                namespace: public
                server-addr: localhost:8848
                password: nacos
                username: nacos
                service: ${spring.application.name}
            #                contextPath: /nacos
#                auto-refresh: true
#                data-id: application

            #    autoconfigure:
#        exclude: org.springframework.cloud.client.serviceregistry.AutoServiceRegistrationAutoConfiguration,org.springframework.cloud.client.serviceregistry.ServiceRegistryAutoConfiguration
#    client: #客户端注册进eureka服务列表内
#        service-url:
#            defaultZone: http://localhost:7001/eureka
            #            defaultZone: http://eureka7001.com:7001/eureka
            #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#    instance:
#        instance-id: ${spring.application.name}:${server.port}
#        prefer-ip-address: true     #访问路径可以显示IP地址

#eureka:
#    client:
#        registry-fetch-interval-seconds: 10
#        eureka-service-url-poll-interval-seconds: 15
#        register-with-eureka: true
#        service-url:
#            defaultZone: http://localhost:7001/eureka

server:
    port: 8081

